@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


LAYOUT_WITH_LEGEND()
'LAYOUT_LEFT_RIGHT()

title Облачная архитектура VitaStore — Целевое состояние (To-Be)
Person(director, "Личный кабинет директора магазина",)

Boundary(store, "Локальный магазин (Каждая из 500+ точек)") {
    Container(tablet_pos, "Кассовое приложение (SaaS POS)", "Тонкий клиент", "Интерфейс кассира")
    ContainerDb(local_cache, "Кэш кассы", , "Автономное хранилище каталога, цен и буфер офлайн-чеков")
    Container(edge_hal, "HAL Агент", , "Абстракция торгового железа от логики SaaS POS. Конфигурация преобразований запросов от SaaS POS в формат терминала")
    Container(fr_device, "Фискальный Регистратор", "Hardware", "Печать чеков, фискальный накопитель")
    Container(pin_pad, "Банковский терминал", "Hardware", "Разнородное оборудование купленных сетей")
}

Boundary(cloud_paas, "Облачная платформа (Managed PaaS / SaaS)") {
    Container(api_gw, "Payment Gateway API", , "Маршрутизация, безопасность, авторизация касс")
    Container(api_gw_dir, "Directors Gateway API ", , "Маршрутизация, безопасность, авторизация касс")
    Container(payment, "Payment", , "Бизнес-логика продаж, учет акций (Promo Engine), учет остатков")
    Container(personal, "Personal", , "Бизнес-логика управления сменами, расчет премий")
    ContainerDb(cloud_db, "Центральная БД касс", , "Консолидированная база данных транзакций и остатков всех точек, условия акций")
    ContainerDb(cloud_db_loyal, "БД системы лояльности", , "Правила лояльности, карточки лояльности, данные клиентов")
    Container(loyalty_saas, "Система лояльности (SaaS)", , "Облачный процессинг баллов, профили клиентов")
    Container(Kafka, "Kafka", ,)
    Container(dictionary_worker, "Dictionary Worker", ,"Синхронизация справочников и акций")
    Container(loyalty_worker, "Loyalty Worker", ,"Синхронизация правил лояльности")
    Container(sales_worker, "Sales Worker", ,"Выгрузка в ERP продаж за период (батчами)")
    Container(fullfillment, "Smart FullFillment", , "Модуль пополнения под заказ. Прием заказов с касс без нагрузки на SAP ERP")
    ContainerDb(fullfillmentDB, "База остатков на складах", ,)
    Container(warehouse_worker, "Warehouse worker", ,"Выгрузка батчами остатков на складах",)
}

Boundary(hq_prem, "Центральный офис (HQ On-Premise)") {
    Container(central_sap, "SAP ERP", , "Мастер-данные товаров, цен, глобальный учет, ведение правил лояльности и акций, ")
}



' Взаимосвязи внутри магазина
Rel(tablet_pos, local_cache, "Чтение каталога / Буферизация чеков в офлайне", )
Rel(tablet_pos, edge_hal, "Запросы на оплату и печать чеков", )
Rel(edge_hal, fr_device, "Управление печатью", )
Rel(edge_hal, pin_pad, "Трансляция универсальных команд", )

' Взаимосвязи Магазин -> Облако
Rel_R(tablet_pos, api_gw, "Платежи", ,)

' Взаимосвязи внутри Облака
Rel(api_gw, payment, "Маршрутизация запросов",)
Rel(payment, loyalty_saas, "Онлайн начисление / Списание бонусов / оплата бонусами", )
Rel(payment, cloud_db, "Запрос правил скидок при сборке корзины",)
Rel(loyalty_saas, cloud_db_loyal, "Запрос правил и актуальных балансов карточек лояльности")
Rel(dictionary_worker, Kafka, "Вычитка изменений")
Rel(dictionary_worker, cloud_db, "Запись изменений")
Rel(loyalty_worker, Kafka, "Вычитка изменений")
Rel(loyalty_worker, cloud_db_loyal, "Запись изменений")
Rel(api_gw_dir, personal, "Маршрутизация запросов")
Rel(api_gw, fullfillment, "Запрос на товар под заказ")
Rel(fullfillment, fullfillmentDB, "запрос остатков на складах")
Rel(warehouse_worker, fullfillmentDB, "обновление остатков на складах")


' Взаимосвязи Облако -> HQ
Rel_L(central_sap, Kafka, "Real-time стриминг изменений цен и номенклатуры", "Apache Kafka")
Rel(sales_worker, cloud_db, "вычитывает продажи за период")
Rel(sales_worker, central_sap, "пишет продажи за период")
Rel_R(personal, central_sap, "Запрос расчета премии, графика смен")
Rel(central_sap, warehouse_worker, "Выгрузка батчами остатков на складах")


Rel(director, api_gw_dir, "запрос ")
@enduml
